"""Home page: index.html"""
from util import *
from config import *
from components import *
from data.events import EVENTS
from data.posts import POSTS
from data.content import *
from render import page, tpl


def build():
    fe = [x for x in EVENTS if x["st"] != "past"][:3]
    FEAT = f'<section><div class="wrap"><div class="shl rv"><div><h2>Featured Events</h2></div><a class="lk" href="events.html">All events →</a></div><div class="feat">{tile(fe[1], True)}{tile(fe[0])}{tile(fe[2])}</div></div></section>'
    pa = POSTS[0]
    INS = f'<section class="alt"><div class="wrap"><div class="shl rv"><div><h2>Latest Insights</h2></div><a class="lk" href="blog.html">All articles →</a></div><div class="ins"><a class="lead rv" href="blog-{pa["s"]}.html"><div class="lim"><img src="{pa["i"]}" alt="{e(pa["t"])}" loading="lazy" width="900" height="560"></div><span class="cat">{pmeta(pa)}</span><h3>{pa["t"]}</h3><p>{pa["ex"]}</p><span class="lk">Read Article →</span></a><div class="side rv">{"".join(pit(x) for x in POSTS[1:3])}</div></div></div></section>'
    SLIDES = [("nyc", False), ("lon", True), ("dxb", False), ("par", False), ("conf", False), ("lights", False)]
    CITY = '<section><div class="wrap">' + head("Across the US, EMEA, and beyond") + '<div class="car" role="region" aria-roledescription="carousel" aria-label="Event and city photography"><div class="ctrack" tabindex="0">' + "".join(f'<div class="cs"><img src="{IM[k]}" alt="{"L1C — Level One Connect" if lg else "City skyline"}" loading="lazy" width="800" height="500">' + (f'<div class="cl"><img src="assets/logo-nav.png" alt="" width="{NW}" height="{NH}"></div>' if lg else "") + "</div>" for k, lg in SLIDES) + '</div><button class="cb2 cprev" type="button" aria-label="Previous photo">‹</button><button class="cb2 cnext" type="button" aria-label="Next photo">›</button></div></div></section>'
    home = f'''<section class="hero"><div class="wrap"><p class="eb rotw rv">Level One Connect &nbsp;/&nbsp; <span id="rw">Executive Networking</span></p><h1 class="rv">Experiences that redefine how leaders meet, think, and decide.</h1><p class="lead rv">Where the world’s most influential senior leaders come together to shape the future across industries.</p><div class="row rv">{CTA("start-your-event.html", "Start Planning Your Event")}{CTA("services.html", "Explore Our Services", "btn ghost")}</div></div></section>
    <section><div class="wrap">{head("Our Premium Services", "We design and deliver high-impact events—from concept to execution—focused on success and ROI.")}<div class="grid3">{"".join(scard(i, s) for i, s in enumerate(SERV))}</div><p class="c">{CTA("services.html", "View Our Services", "btn ghost dk")}</p></div></section>
    <section class="alt"><div class="wrap two-col"><div class="rv pic"><img src="{IM["team"]}" alt="Executives in discussion at a corporate event" loading="lazy" width="900" height="700"></div><div class="rv"><p class="eb">About L1C</p><h2>Redefining Business &amp; Networking Gatherings</h2><p class="mut">Your trusted partner in professional event management since 2020</p><p>Transforming how executives connect and convene. As a global event partner, we design and execute executive gatherings across the US, EMEA, and beyond—bringing senior leaders together through experiences that enable connection, collaboration, and growth.</p><dl><dt>Strategic Approach</dt><dd>Every event is designed with clear business objectives and measurable outcomes in mind.</dd><dt>Local Expertise</dt><dd>We collaborate with leading organizations across various industries to deliver exceptional events.</dd><dt>Global Standards</dt><dd>International best practices combined with local insights for exceptional results.</dd></dl>{CTA("about.html", "Partner With Us")}</div></div></section>
    <section><div class="wrap">{head("Our Strategic Process", "A systematic approach to delivering exceptional events that drive results.")}<div class="steps" role="tablist" aria-label="Process steps">{"".join(f'<button role="tab" class="{"on" if i == 0 else ""}" aria-selected="{"true" if i == 0 else "false"}" data-i="{i}"><span>0{i + 1}</span>{p[0]}</button>' for i, p in enumerate(PROC))}</div>{"".join(f'<div class="sp {"on" if i == 0 else ""}" role="tabpanel"><h3>0{i + 1} — {p[0]}</h3><p>{p[2]}</p></div>' for i, p in enumerate(PROC))}</div></section>
    {stats()}{CITY}{FEAT}{INS}{cta()}
    <section><div class="wrap two-col"><div class="rv"><h2>Contact</h2><p>London, United Kingdom</p><p><a href="mailto:{EMAIL}">{EMAIL}</a></p><p>{" · ".join(PHONES)}</p>{CTA("tel:" + PHONES[0].replace(" ", ""), "Call Now")}</div><div class="rv" id="form">{form()}</div></div></section>'''
    page("index", "L1C — Level One Connect | Premium Corporate Events & Executive Networking", "L1C — Level One Connect designs premium corporate events and executive networking gatherings for senior leaders across the US, EMEA and beyond.", home)
