import os, json, shutil, glob, zipfile, html as H
SITE = "https://www.l1c.example"  # replace with the real domain
EMAIL = "info@l1c.example"        # replace with the real email
PHONES = ["+44 20 0000 0000"]  # replace with the real London number
OUT = "site"
U = lambda i: f"https://images.unsplash.com/photo-{i}?auto=format&fit=crop&w=1600&q=75"
IM = dict(hero=U("1511795409834-ef04bbd61622"), team=U("1556761175-5973dc0f32e7"), net=U("1511578314322-379afb476865"),
          conf=U("1505373877841-8d25f7d46678"), conf2=U("1540575467063-178a50c2df87"), dinner=U("1519167758481-83f550bb49b3"),
          dine2=U("1414235077428-338989a2e8c0"), cons=U("1486406146926-c627a92ad1ab"), off=U("1477959858617-67f85cf4f1df"),
          lights=U("1492684223066-81342ee5ff30"), nyc=U("1480714378408-67cf0d13bc1b"), lon=U("1513635269975-59663e0ac1ad"),
          dxb=U("1512453979798-5ea266f8880c"), par=U("1502602898657-3e91760cbb34"))
e = H.escape
THEME = '''<script>document.documentElement.classList.add("js");try{document.documentElement.dataset.theme=localStorage.getItem("l1c-theme")||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light")}catch(e){document.documentElement.dataset.theme="light"}</script>'''
TT = '<button id="tt" class="tt" type="button" aria-label="Switch between dark and light mode"><svg class="moon" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg><svg class="sun" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg></button>'
import re
CSS = re.sub(r"/\*.*?\*/", "", open("style.css").read(), flags=re.S)
APP = re.sub(r"/\*.*?\*/", "", open("app.js").read(), flags=re.S)
CFG = 'window.L1C_ENDPOINT = ""; window.L1C_EMAIL = "' + EMAIL + '";'
shutil.rmtree(OUT, ignore_errors=True); os.makedirs(OUT + "/assets")
if os.path.exists("logo.png"):  # official L1C logo, used unchanged
    shutil.copy("logo.png", f"{OUT}/assets/logo.png"); LOGO = "assets/logo.png"
else:
    LOGO = "assets/logo.svg"
    open(f"{OUT}/assets/logo.svg", "w").write('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 40"><text x="0" y="31" font-family="Inter,Arial,sans-serif" font-weight="800" font-size="34" fill="#fff">L1<tspan fill="#5170FF">C</tspan></text></svg>')

import base64
LOGO_URI = "data:image/png;base64," + base64.b64encode(open("logo-inline.png", "rb").read()).decode() if os.path.exists("logo-inline.png") else LOGO
b64 = lambda f: "data:image/png;base64," + base64.b64encode(open(f, "rb").read()).decode()
LOGO_NAV, LOGO_FAV = b64("logo-nav.png"), b64("logo-fav.png")
NH = 38; NW = round(NH * 188 / 76)
NAV = [("index", "Home"), ("services", "Services"), ("about", "About"), ("process", "Process"), ("events", "Events"), ("blog", "Blog"), ("contact", "Contact")]
EVENTS = [
 dict(s="executive-leaders-dinner", t="Executive Leaders Dinner", c="Leadership Dinners", d="2026-11-12", tm="19:00", l="London, UK", st="upcoming", i=IM["dinner"], ds="An invitation-only dinner where senior leaders exchange ideas in an intimate setting."),
 dict(s="technology-leadership-summit", t="Technology Leadership Summit", c="Business Summits", d="2027-02-18", tm="09:00", l="London, UK", st="featured", i=IM["conf"], ds="A one-day summit for technology and business decision-makers on strategy and growth."),
 dict(s="executive-networking-evening", t="Executive Networking Evening", c="Executive Networking", d="2027-04-22", tm="18:30", l="Paris, France", st="upcoming", i=IM["net"], ds="A curated evening connecting decision-makers across industries."),
 dict(s="leaders-roundtable-series", t="Leaders Roundtable Series", c="Leadership Dinners", d="2026-12-03", tm="19:00", l="London, UK", st="upcoming", i=IM["dine2"], ds="A small-group roundtable dinner for senior leaders to discuss the decisions shaping their industries."),
 dict(s="cx-ai-executive-forum", t="CX and AI Executive Forum", c="Technology Events", d="2027-03-10", tm="10:00", l="Munich, Germany", st="upcoming", i=IM["cons"], ds="An executive forum on customer experience and AI, for technology and CX decision-makers."),
 dict(s="annual-business-conference", t="Annual Business Conference", c="Conferences", d="2027-05-14", tm="09:30", l="London, UK", st="featured", i=IM["conf2"], ds="A full-day conference bringing together business leaders, partners and sponsors."),
 dict(s="product-launch-evening", t="Product Launch Evening", c="Product Launches", d="2027-06-04", tm="18:00", l="London, UK", st="upcoming", i=IM["lights"], ds="An evening launch experience for invited partners, press and clients."),
 dict(s="executive-dinner-series-2025", t="Executive Dinner Series 2025", c="Leadership Dinners", d="2025-05-15", tm="19:30", l="London, UK", st="past", i=IM["dine2"], ds="A dinner series that brought senior leaders together for candid conversations."),
 dict(s="technology-leaders-meetup", t="Technology Leaders Meetup", c="Technology Events", d="2025-03-20", tm="17:30", l="Dublin, Ireland", st="past", i=IM["off"], ds="A meetup for technology leaders and their partners."),
 dict(s="product-showcase-2025", t="Product Showcase", c="Product Launches", d="2025-10-09", tm="17:00", l="London, UK", st="past", i=IM["lights"], ds="A showcase bringing partners and press together for a product reveal."),
]
POSTS = [
 dict(s="start-with-the-decision-not-the-venue", t="Start with the decision, not the venue", c="Event Strategy", d="2026-09-10", r=4, i=IM["cons"], ex="Before you book a room, decide what you want people to do differently afterwards.",
      b=["Most event briefs begin with a date and a venue. It works better to begin with a sentence: after this event, we want these people to have done this. A client signed, a partnership started, a team agreed on a plan.", "Once that sentence exists, most other choices get easier. It tells you who needs to be in the room, how long they should stay, and whether you need a stage at all or simply a long table and twelve chairs.", "It also gives you something to measure. If the goal was three follow-up meetings, count the follow-up meetings. That is a better report than attendance figures."]),
 dict(s="why-smaller-rooms-make-better-conversations", t="Why smaller rooms make better conversations", c="Executive Networking", d="2026-08-21", r=3, i=IM["net"], ex="A short guest list, a seated format and a follow-up plan do most of the work.",
      b=["Senior people rarely lack events to attend. What they lack is time, so the question they ask is whether the people in the room are worth meeting.", "A seated dinner for twenty usually does more than a reception for two hundred. Everyone talks to everyone, and nobody spends the evening looking over someone's shoulder.", "The work continues after the evening. A short, personal note within two days, with introductions where they make sense, is what turns a good dinner into a working relationship."]),
 dict(s="working-out-whether-an-event-paid-off", t="Working out whether an event paid off", c="Corporate Events", d="2026-07-02", r=4, i=IM["off"], ex="Agree what success looks like before the invitations go out, then keep the tracking simple.",
      b=["Return on an event is easy to argue about afterwards and hard to prove unless the measures are agreed beforehand. Decide them at the start, with the people who will judge the result.", "Pick a small number. Meetings booked, deals moved forward, partners introduced or feedback scores are usually enough. Collect them the same way every time.", "Then look at what the numbers say and change something for the next event. Most of the value in measuring is in that second step."]),

 dict(s="ai-in-the-room", t="AI in the room: where it helps an event and where it gets in the way", c="Technology", d="2026-09-28", r=5, i=IM["team"], ex="Useful for the people running an event, a poor substitute for the people attending it.",
      b=["AI is now part of most events teams' daily tools, whether or not anyone announced it. It drafts invitations, tidies guest lists, summarises feedback forms and turns a rough agenda into a clean one. Used like this it saves hours, and the hours go back into the parts of the job that need a person.", "It gets in the way when it sits between the host and the guest. An automated greeting, a generic follow-up or a matchmaking suggestion nobody has checked can make a senior guest feel like a record in a database. At an invitation-only dinner, that costs far more than the time it saved.", "A simple rule works well: let AI prepare, and let people decide and speak. Anything that carries your name to a guest should be read first by someone who knows that guest."]),
 dict(s="five-practical-ways-ai-can-save-an-events-team-time", t="Five practical ways AI can save an events team time", c="Technology", d="2026-09-17", r=4, i=IM["cons"], ex="Small, unglamorous uses that add up over a busy season.",
      b=["The useful applications are rarely the dramatic ones. They are small tasks that eat a week over a season: first drafts of invitations and reminders, summarising a long thread of supplier emails, turning notes from a planning call into an action list, translating a programme for an international audience, and sorting feedback comments into themes.", "Each of these produces a draft, not a finished product. Names, dates, figures and tone still need checking by someone who knows the event. Treat the output the way you would treat work from a new colleague: quick, helpful and not yet signed off.", "Be careful what you paste in. Guest lists and contracts contain other people's information, so check what your tools do with it, and what your own policies allow, before you use them."]),
 dict(s="why-in-person-still-matters", t="Why in-person still matters in a world of video calls", c="Industry Insights", d="2026-09-01", r=3, i=IM["net"], ex="Video is efficient for updates. Trust is still built in the same room.",
      b=["Video calls are very good at moving information. They are less good at the things that happen around the information: the quiet word before a session, the second coffee, the moment you realise the person next to you is dealing with the same problem.", "Those moments are why people still travel to meet. A room full of peers gives a leader something a call cannot, which is a sense of how others are thinking about the same decisions and the chance to ask a follow-up question straight away.", "That is also the argument for keeping events small, well hosted and worth the journey. If people are going to give up a day, the day should earn it."]),
 dict(s="how-to-choose-a-city-for-an-international-event", t="How to choose a city for an international event", c="Corporate Events", d="2026-08-10", r=5, i=IM["nyc"], ex="Flights, time zones and venues matter more than the postcard.",
      b=["A city can look right in a brochure and be hard on the day. Start with the practical questions. Where are most guests travelling from, and how many connections does that involve? Are there direct flights at sensible times? Does the time zone suit people joining remotely?", "Then look at venues. Major business cities usually have hotels with proper meeting space, restaurants with private rooms and a handful of distinctive spaces, but the good ones book months ahead, especially around large trade fairs and public holidays. Check the local calendar before you fix a date.", "Finally, think about the guests. Visa requirements, accessibility, dietary needs and local customs should shape the plan from the beginning, not arrive as problems in the final weeks."]),
 dict(s="what-makes-a-keynote-worth-sitting-through", t="What makes a keynote worth sitting through", c="Leadership", d="2026-07-28", r=4, i=IM["conf"], ex="A clear argument, a short running time and room for questions.",
      b=["The best keynotes make one argument and stick to it. The speaker knows what they want the room to think differently about, and every story and slide serves that point. If a talk can be summed up in a single sentence, it is usually a good one.", "Length matters too. Twenty tight minutes followed by real questions will beat forty minutes of material nobody asked for. Brief speakers on the audience, the time slot and what the previous session covered, so they do not repeat each other.", "As the host, protect the questions. A moderator who has read the talk in advance and prepared three good questions makes the speaker, and the session, better."]),
 dict(s="working-with-sponsors-without-an-advert", t="Working with sponsors without turning the day into an advert", c="Event Strategy", d="2026-07-14", r=4, i=IM["lights"], ex="Sponsors want visibility. Guests want a useful day. You can give both.",
      b=["Sponsors fund a lot of good events, and they are right to expect something in return. Problems start when that return is a series of product pitches the audience did not ask for.", "A better approach is to agree early what each sponsor can offer the guests: a practical session, a roundtable they host, or an introduction to someone relevant. Visibility follows from being useful, and sponsors tend to renew when their name is linked with a session people enjoyed.", "Put the rules in writing before the event, including speaking time, branding and any follow-up with guest details, so everyone knows where the lines are."]),
 dict(s="greener-events-without-the-gimmicks", t="Greener events without the gimmicks", c="Industry Insights", d="2026-06-19", r=4, i=IM["off"], ex="A few good decisions on travel, food and materials make most of the difference.",
      b=["Most of an event's environmental impact comes from three things: how people travel, what they eat, and how much is built, printed and thrown away. Start with those and you have covered most of it.", "Choose venues that are easy to reach by train or public transport, order food for the people who will actually attend, and design signage and staging that can be used again. None of this makes an event feel smaller.", "Be honest in how you describe it. Say what you changed and what you measured, and avoid big claims you cannot support."]),
 dict(s="advice-for-first-time-panellists", t="Advice for first-time panellists", c="Leadership", d="2026-06-05", r=3, i=IM["conf2"], ex="Prepare two points, listen to the others and keep your answers short.",
      b=["Being asked to join a panel is a good sign, and a slightly nerve-racking one. The preparation is simpler than it feels: decide on two points you want to make, and have one example for each.", "During the session, listen. The best panels sound like a conversation, so respond to what the previous speaker said rather than waiting for your turn to recite. Keep answers to about a minute and leave room for the others.", "Ask the moderator beforehand what the first question will be, and agree who will cover what so you do not all give the same answer."]),
 dict(s="looking-after-guest-data-at-your-event", t="Looking after guest data at your event", c="Technology", d="2026-05-22", r=4, i=IM["team"], ex="Collect what you need, say why, keep it safe and delete it when you are done.",
      b=["Every event collects personal information: names, email addresses, job titles, sometimes dietary needs. Treat it with the same care as the event itself, because guests notice when it is handled badly.", "Four habits cover the basics. Ask only for what you need. Tell people why you are asking and what will happen to it. Store it somewhere secure, with access limited to those who need it. Delete it when you no longer have a reason to keep it.", "The rules that apply depend on where your guests live and what you do with the data, so check with a qualified adviser rather than relying on a blog post, including this one."]),
]
POSTS.sort(key=lambda p: p["d"], reverse=True)

SERV = [("Corporate Event Planning", "From product launches to annual conferences, we design and execute events that align with your brand identity and business objectives, ensuring seamless experiences that exceed expectations.", "Learn More", "Inquire About Corporate Events", ["Full-Service Planning", "Brand Integration", "Vendor Management", "Budget Management", "ROI Tracking"], IM["conf"]),
 ("Executive Networking", "Strategic gatherings designed to connect industry leaders, decision-makers from Fortune 500 companies, and influencers. We create environments for meaningful business relationships that drive growth and opportunity.", "Explore Networking", "Plan a Networking Event", ["Targeted Invitations", "Strategic Matchmaking", "Industry-Specific Events", "Follow-up Support", "Exclusive Venues"], IM["net"]),
 ("Strategic Event Consulting", "Expert guidance on event strategy, audience engagement, and ROI measurement. We ensure your events deliver tangible business results and strengthen your organization's market position.", "Get Consultation", "Schedule a Consultation", ["Event Strategy Development", "Audience Analysis", "Technology Integration", "Sustainability Planning", "Crisis Management"], IM["cons"])]
EXTRA = [("Speaker Management", "Comprehensive speaker coordination including sourcing, contracting, briefing, and logistics."), ("Hybrid Event Production", "Seamless integration of in-person and virtual components."), ("Post-Event Analysis", "Comprehensive reporting and analysis to measure ROI and gather attendee feedback."), ("Team Building Events", "Customized team building experiences."), ("Award Ceremonies", "Premium award ceremonies recognizing achievement."), ("International Events", "Global event management with cross-cultural communication and international logistics expertise.")]
PROC = [("Discovery & Strategy", "Discovery & Strategy Development", "We begin by understanding your business objectives, target audience, and desired outcomes to create a strategic event blueprint.", ["Initial Consultation", "Audience Analysis", "Goal Setting", "Budget Planning"], "2–4 Weeks"),
 ("Concept Development", "Concept & Design Phase", "Our creative team designs a unique event concept tailored to your specific requirements, audience, and brand identity.", ["Creative Concepting", "Brand Integration", "Venue Selection", "Program Design"], "3–6 Weeks"),
 ("Planning & Coordination", "Planning & Coordination", "Meticulous planning of every detail, from venue selection and speaker coordination to logistics and technology setup.", ["Detailed Planning", "Logistics Management", "Technology Setup", "Speaker Management"], "4–12 Weeks"),
 ("Execution & Management", "Execution & Post-Event Analysis", "On-site management ensuring flawless execution, seamless attendee experience, and real-time problem-solving.", ["On-Site Management", "Attendee Experience", "Real-time Adjustments", "ROI Measurement"], "2–4 Weeks Post-Event")]
PRIN = ["Strategic Alignment", "Collaborative Approach", "Data-Driven Decisions", "Risk Management", "Continuous Improvement", "Sustainability Focus"]
CASES = [("Technology Leaders Summit 2023", "Technology Conference", "500+ industry leaders from across the region.", [("92%", "Attendee Satisfaction"), ("45+", "Partnerships Formed"), ("280%", "ROI Achieved")]),
 ("Business Leaders Forum", "Executive Networking", "150+ C-level executives from four countries.", [("85%", "New Connections"), ("€2.3M", "Deals Facilitated"), ("97%", "Would Attend Again")]),
 ("Innovation Product Reveal", "Product Launch", "A multi-sensory product launch for a leading technology company.", [("150%", "Media Coverage"), ("3.2K", "Social Media Reach"), ("€850K", "Pre-orders Generated")])]
STATS = [("100", "+", "Events Successfully Managed"), ("98", "%", "Client Satisfaction Rate"), ("1000", "+", "Executives Connected"), ("120", "+", "Corporate Partners")]
ORG = {"@context": "https://schema.org", "@type": "Organization", "name": "Level One Connect", "alternateName": "L1C", "url": SITE, "logo": f"{SITE}/{LOGO}",
       "description": "Premium corporate event management and executive networking company.", "address": {"@type": "PostalAddress", "addressLocality": "London", "addressCountry": "GB"}, "telephone": PHONES[0], "email": EMAIL}
fd = lambda d: __import__("datetime").date.fromisoformat(d).strftime("%d %b %Y")
CTA = lambda h, t, cls="btn": f'<a class="{cls}" href="{h}">{t}</a>'
JS = lambda o: f'<script type="application/ld+json">{json.dumps(o)}</script>'

def crumbs(items):
    return JS({"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": n + 1, "name": a, "item": f"{SITE}/{b}"} for n, (a, b) in enumerate(items)]})

def page(f, title, desc, body, extra="", img=IM["hero"], crumb=None, og="website"):
    nav = "".join(f'<li><a href="{k}.html"{" aria-current=page" if f == k or (f.startswith("event-") and k == "events") or (f.startswith("blog-") and k == "blog") else ""}>{v}</a></li>' for k, v in NAV)
    fl = "".join(f'<li><a href="{k}.html">{v if k != "process" else "Our Process"}</a></li>' for k, v in NAV)
    can = f"{SITE}/{'' if f == 'index' else f + '.html'}"
    full = f"{title} | L1C — Level One Connect" if f != "index" else title
    cr = crumbs([("Home", "")] + crumb) if crumb else ""
    out = f'''<!DOCTYPE html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>{e(full)}</title><meta name="description" content="{e(desc)}"><link rel="canonical" href="{can}">

<meta name="referrer" content="strict-origin-when-cross-origin"><meta name="theme-color" content="#000000">
<meta property="og:locale" content="en_GB"><meta property="og:type" content="{og}"><meta property="og:site_name" content="L1C — Level One Connect"><meta property="og:title" content="{e(full)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{can}"><meta property="og:image" content="{img}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{e(full)}"><meta name="twitter:description" content="{e(desc)}"><meta name="twitter:image" content="{img}">
<link rel="icon" type="image/png" href="{LOGO_FAV}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"><style>{CSS}</style>
{JS(ORG)}{cr}{extra}{THEME}</head><body>
<a class="skip" href="#main">Skip to content</a>
<header id="hd"><div class="wrap bar"><a class="logo" href="index.html" aria-label="L1C — Level One Connect, home"><img src="{LOGO_NAV}" alt="L1C — Level One Connect" class="lg" width="{NW}" height="{NH}"></a>
<nav aria-label="Main"><ul id="menu">{nav}<li class="mcta"><a class="btn" href="start-your-event.html">Start Your Event</a></li></ul></nav>
<a class="btn hcta" href="start-your-event.html">Start Your Event</a>{TT}<button id="mb" aria-label="Open menu" aria-expanded="false" aria-controls="menu"><span></span><span></span></button></div></header>
<main id="main">{body}</main>
<footer><div class="wrap fg"><div><a class="logo" href="index.html"><img src="{LOGO_NAV}" alt="L1C — Level One Connect" class="lg" width="{NW}" height="{NH}" loading="lazy"></a><p class="fn">Level One Connect</p><p class="mut">Executive networking across industries and decision-makers.</p></div>
<div><h3>Quick Links</h3><ul>{fl}</ul></div><div><h3>Legal</h3><ul><li><a href="privacy.html">Privacy Policy</a></li><li><a href="terms.html">Terms &amp; Conditions</a></li><li><a href="cookies.html">Cookie Policy</a></li></ul></div>
<div><h3>Contact</h3><ul><li>London, United Kingdom</li><li><a href="mailto:{EMAIL}">{EMAIL}</a></li>{"".join(f'<li><a href="tel:{p.replace(" ", "")}">{p}</a></li>' for p in PHONES)}</ul></div></div>
<div class="wrap fb"><p>© 2026 L1C — Level One Connect. All rights reserved.</p><p>Website crafted by <a href="https://101webstudio.github.io/" target="_blank" rel="noopener noreferrer">101WebStudio</a></p></div></footer>
<script>{CFG}
{APP}</script></body></html>'''
    open(f"{OUT}/{f}.html", "w", encoding="utf-8").write(out)

def hero(h, sub, im, eyebrow=""):
    return f'<section class="ph glow"><div class="wrap"><p class="eb">{eyebrow}</p><h1>{h}</h1><p class="lead">{sub}</p></div></section>'
def head(t, s="", c=""):
    return f'<div class="sh rv {c}"><h2>{t}</h2>{f"<p>{s}</p>" if s else ""}</div>'
def scard(i, s):
    return f'<article class="card rv"><span class="n">0{i + 1}</span><h3>{s[0]}</h3><p>{s[1]}</p><a class="lk" href="services.html">{s[2]} →</a></article>'
def stats():
    return '<section class="dark"><div class="wrap sg">' + "".join(f'<div class="rv"><b data-n="{n}" data-s="{s}">{n}{s}</b><span>{l}</span></div>' for n, s, l in STATS) + '</div></section>'
def ecard(v):
    return f'<article class="card ev rv"><a href="event-{v["s"]}.html" class="im"><img src="{v["i"]}" alt="{e(v["t"])}" loading="lazy" width="800" height="500"></a><div class="cb"><span class="tag">{v["c"]}</span><h3><a href="event-{v["s"]}.html">{v["t"]}</a></h3><p class="mut">{fd(v["d"])} · {v["tm"]} · {v["l"]}</p><p>{v["ds"]}</p><a class="lk" href="event-{v["s"]}.html">View Event →</a></div></article>'
def dq(v):
    d = __import__("datetime").date.fromisoformat(v["d"])
    return e(" ".join([v["t"], v["c"], v["l"], d.strftime("%d %B %Y %b")]).lower())
def erow(v):
    return f'<article class="card ec rv" data-q="{dq(v)}"><a class="eth" href="event-{v["s"]}.html" tabindex="-1" aria-hidden="true"><img src="{v["i"]}" alt="" loading="lazy" width="400" height="225"></a><div class="ecb"><span class="tag">{v["c"]}</span><h3><a href="event-{v["s"]}.html">{v["t"]}</a></h3><p>{fd(v["d"])} · {v["tm"]} · {v["l"]}</p><a class="btn sm ghost dk" href="event-{v["s"]}.html">View Event</a></div></article>'
def bcard(p):
    return f'<article class="card ev rv"><a href="blog-{p["s"]}.html" class="im"><img src="{p["i"]}" alt="{e(p["t"])}" loading="lazy" width="800" height="500"></a><div class="cb"><span class="tag">{p["c"]}</span><p class="mut">{fd(p["d"])} · {p["r"]} min read</p><h3><a href="blog-{p["s"]}.html">{p["t"]}</a></h3><p>{p["ex"]}</p><a class="lk" href="blog-{p["s"]}.html">Read Article →</a></div></article>'
def cta():
    return f'<section class="dark cta"><div class="wrap rv"><h2>Let\'s Create Something Exceptional Together</h2><p class="lead">Whether you\'re planning a conference, executive networking event, or corporate gathering, our team is ready to help you create an unforgettable experience that delivers real business value.</p><div class="row">{CTA("start-your-event.html", "Start Your Event Journey")}{CTA("contact.html#form", "Contact Our Team", "btn ghost")}</div></div></section>'

HP = '<div class="hp" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div>'
CONSENT = '<div class="f"><label class="cb1"><input type="checkbox" id="consent" name="consent" required><span>I agree to be contacted about this request. See our <a href="privacy.html">Privacy Policy</a>.</span></label><small class="err"></small></div>'
def fld(i, l, t="text", req=False, opts=None, ph="", pl="", mx=150, ac="", rows=5):
    r, st = (" required", " *") if req else ("", "")
    a = f' autocomplete="{ac}"' if ac else ""
    p = f' placeholder="{e(pl)}"' if pl else ""
    if t == "select":
        c = f'<select id="{i}" name="{i}"{r}><option value="">{ph or "Select"}</option>' + "".join(f"<option>{x}</option>" for x in opts) + "</select>"
    elif t == "area":
        c = f'<textarea id="{i}" name="{i}" rows="{rows}"{r}{p} maxlength="2000"></textarea>'
    else:
        c = f'<input id="{i}" name="{i}" type="{t}"{r}{p} maxlength="{mx}"{a}>'
    return f'<div class="f"><label for="{i}">{l}{st}</label>{c}<small class="err"></small></div>'
two = lambda *x: '<div class="two">' + "".join(x) + "</div>"
def chk(name, label, opts):
    return f'<fieldset class="chk" data-name="{name}"><legend>{label}</legend><div class="cg">' + "".join(f'<label><input type="checkbox" value="{x}"> {x}</label>' for x in opts) + "</div></fieldset>"
sub = lambda n, t, *x: f'<div class="fs"><h2 class="fh"><b>{n}</b>{t}</h2>' + "".join(x) + "</div>"
def form():
    op = lambda l: "".join(f"<option>{x}</option>" for x in l)
    return f'''<form id="cf" novalidate class="form" data-subject="Event enquiry" aria-label="Contact form"><div class="hp" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div>
<div class="two"><div class="f"><label for="name">Full Name *</label><input id="name" name="name" required maxlength="100" autocomplete="name"><small class="err"></small></div><div class="f"><label for="company">Company *</label><input id="company" name="company" required maxlength="120" autocomplete="organization"><small class="err"></small></div></div>
<div class="two"><div class="f"><label for="email">Email Address *</label><input id="email" name="email" type="email" required maxlength="150" autocomplete="email"><small class="err"></small></div><div class="f"><label for="phone">Phone Number</label><input id="phone" name="phone" type="tel" maxlength="30" autocomplete="tel"><small class="err"></small></div></div>
<div class="two"><div class="f"><label for="type">Event Type *</label><select id="type" name="type" required><option value="">Select event type</option>{op(["Conference / Summit", "Executive Networking", "Product Launch", "Gala Dinner / Awards", "Team Building", "Corporate Training", "Other"])}</select><small class="err"></small></div>
<div class="f"><label for="size">Estimated Attendees *</label><select id="size" name="size" required><option value="">Select attendees</option>{op(["10–50", "50–100", "100–200", "200–500", "500+"])}</select><small class="err"></small></div></div>
<div class="f"><label for="msg">Tell us about your event *</label><textarea id="msg" name="msg" rows="5" required maxlength="2000"></textarea><small class="err"></small></div>
<button class="btn" type="submit"><span>Send Message</span></button><p class="st" role="status" aria-live="polite"></p></form>'''

def tile(v, big=False):
    return f'<a class="tile rv{" big" if big else ""}" href="event-{v["s"]}.html"><img src="{v["i"]}" alt="{e(v["t"])}" loading="lazy" width="900" height="600"><div class="tc"><span class="tag2">{v["c"]}</span><h3>{v["t"]}</h3><p>{fd(v["d"])} · {v["l"]}</p></div><span class="go" aria-hidden="true">↗</span></a>'
def pmeta(p):
    return f'{p["c"]} · {fd(p["d"])} · {p["r"]} min read'
def pit(p):
    return f'<a class="it" href="blog-{p["s"]}.html"><img src="{p["i"]}" alt="{e(p["t"])}" loading="lazy" width="300" height="300"><div><span class="cat">{pmeta(p)}</span><h3>{p["t"]}</h3></div></a>'
fe = [x for x in EVENTS if x["st"] != "past"][:3]
FEAT = f'<section><div class="wrap"><div class="shl rv"><div><h2>Featured Events</h2></div><a class="lk" href="events.html">All events →</a></div><div class="feat">{tile(fe[1], True)}{tile(fe[0])}{tile(fe[2])}</div></div></section>'
pa = POSTS[0]
INS = f'<section class="alt"><div class="wrap"><div class="shl rv"><div><h2>Latest Insights</h2></div><a class="lk" href="blog.html">All articles →</a></div><div class="ins"><a class="lead rv" href="blog-{pa["s"]}.html"><div class="lim"><img src="{pa["i"]}" alt="{e(pa["t"])}" loading="lazy" width="900" height="560"></div><span class="cat">{pmeta(pa)}</span><h3>{pa["t"]}</h3><p>{pa["ex"]}</p><span class="lk">Read Article →</span></a><div class="side rv">{"".join(pit(x) for x in POSTS[1:3])}</div></div></div></section>'
SLIDES = [("nyc", False), ("lon", True), ("dxb", False), ("par", False), ("conf", False), ("lights", False)]
CITY = '<section><div class="wrap">' + head("Across the US, EMEA, and beyond") + '<div class="car" role="region" aria-roledescription="carousel" aria-label="Event and city photography"><div class="ctrack" tabindex="0">' + "".join(f'<div class="cs"><img src="{IM[k]}" alt="{"L1C — Level One Connect" if lg else "City skyline"}" loading="lazy" width="800" height="500">' + (f'<div class="cl"><img src="{LOGO_NAV}" alt="" width="{NW}" height="{NH}"></div>' if lg else "") + "</div>" for k, lg in SLIDES) + '</div><button class="cb2 cprev" type="button" aria-label="Previous photo">‹</button><button class="cb2 cnext" type="button" aria-label="Next photo">›</button></div></div></section>'
SEARCH = '<section class="sb"><div class="wrap"><form class="sbar" role="search" onsubmit="return false"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input id="es" type="search" placeholder="Search events by name, city or category" aria-label="Search events" autocomplete="off"></form><p id="ecount" class="mut" role="status" aria-live="polite"></p></div></section>'
# ---------- pages
home = f'''<section class="hero glow"><div class="wrap"><p class="eb rotw rv">Level One Connect &nbsp;/&nbsp; <span id="rw">Executive Networking</span></p><h1 class="rv">Experiences that redefine how leaders meet, think, and decide.</h1><p class="lead rv">Where the world’s most influential senior leaders come together to shape the future across industries.</p><div class="row rv">{CTA("start-your-event.html", "Start Planning Your Event")}{CTA("services.html", "Explore Our Services", "btn ghost")}</div></div></section>
<section><div class="wrap">{head("Our Premium Services", "We design and deliver high-impact events—from concept to execution—focused on success and ROI.")}<div class="grid3">{"".join(scard(i, s) for i, s in enumerate(SERV))}</div><p class="c">{CTA("services.html", "View Our Services", "btn ghost dk")}</p></div></section>
<section class="alt"><div class="wrap two-col"><div class="rv pic"><img src="{IM["team"]}" alt="Executives in discussion at a corporate event" loading="lazy" width="900" height="700"></div><div class="rv"><p class="eb">About L1C</p><h2>Redefining Business &amp; Networking Gatherings</h2><p class="mut">Your trusted partner in professional event management since 2020</p><p>Transforming how executives connect and convene. As a global event partner, we design and execute executive gatherings across the US, EMEA, and beyond—bringing senior leaders together through experiences that enable connection, collaboration, and growth.</p><dl><dt>Strategic Approach</dt><dd>Every event is designed with clear business objectives and measurable outcomes in mind.</dd><dt>Local Expertise</dt><dd>We collaborate with leading organizations across various industries to deliver exceptional events.</dd><dt>Global Standards</dt><dd>International best practices combined with local insights for exceptional results.</dd></dl>{CTA("about.html", "Partner With Us")}</div></div></section>
<section><div class="wrap">{head("Our Strategic Process", "A systematic approach to delivering exceptional events that drive results.")}<div class="steps" role="tablist" aria-label="Process steps">{"".join(f'<button role="tab" class="{"on" if i == 0 else ""}" aria-selected="{"true" if i == 0 else "false"}" data-i="{i}"><span>0{i + 1}</span>{p[0]}</button>' for i, p in enumerate(PROC))}</div>{"".join(f'<div class="sp {"on" if i == 0 else ""}" role="tabpanel"><h3>0{i + 1} — {p[0]}</h3><p>{p[2]}</p></div>' for i, p in enumerate(PROC))}</div></section>
{stats()}{CITY}{FEAT}{INS}{cta()}
<section><div class="wrap two-col"><div class="rv"><h2>Contact</h2><p>London, United Kingdom</p><p><a href="mailto:{EMAIL}">{EMAIL}</a></p><p>{" · ".join(PHONES)}</p>{CTA("tel:" + PHONES[0].replace(" ", ""), "Call Now")}</div><div class="rv" id="form">{form()}</div></div></section>'''
page("index", "L1C — Level One Connect | Premium Corporate Events & Executive Networking", "L1C — Level One Connect designs premium corporate events and executive networking gatherings for senior leaders across the US, EMEA and beyond.", home)

SVL = ["start-your-event.html?type=Conference+%2F+Summit", "start-your-event.html?type=Executive+Networking", "contact.html"]
sv = ""
for i, s in enumerate(SERV):
    sv += f'<section class="{"alt" if i % 2 else ""}"><div class="wrap two-col {"rev" if i % 2 else ""}"><div class="rv pic"><img src="{s[5]}" alt="{s[0]}" loading="lazy" width="900" height="700"></div><div class="rv"><h2>{s[0]}</h2><p>{s[1]}</p><ul class="ck">{"".join(f"<li>{x}</li>" for x in s[4])}</ul>{CTA(SVL[i], s[3])}</div></div></section>'
sv += f'<section class="dark"><div class="wrap">{head("Additional Services")}<div class="grid3">{"".join(f"<article class=card><h3>{a}</h3><p>{b}</p></article>" for a, b in EXTRA)}</div></div></section><section class="cta"><div class="wrap rv"><h2>Ready to Transform Your Next Event?</h2>{CTA("start-your-event.html", "Get Started Today")}</div></section>'
page("services", "Our Premium Event Services", "Corporate event planning, executive networking and strategic event consulting from L1C — Level One Connect.", hero("Our Premium Event Services", "Comprehensive event solutions designed to elevate your corporate gatherings and maximize ROI.", IM["conf"]) + sv, crumb=[("Services", "services.html")])

ab = f'''{hero("About Level One Connect", "Your trusted partner in professional event management since 2020", IM["team"])}<section><div class="wrap two-col"><div class="rv"><h2>Redefining Business &amp; Networking Gatherings</h2><p>Transforming how executives connect and convene. As a global event partner, we design and execute executive gatherings across the US, EMEA, and beyond—bringing senior leaders together through experiences that enable connection, collaboration, and growth.</p><dl><dt>Strategic Approach</dt><dd>Every event is designed with clear business objectives and measurable outcomes in mind.</dd><dt>Industry Expertise</dt><dd>Deep understanding of technology and business trends.</dd><dt>Global Standards</dt><dd>International best practices combined with local insights for exceptional results.</dd></dl>{CTA("contact.html", "Partner With Us Today")}</div><div class="rv pic"><img src="{IM["off"]}" alt="City business district" loading="lazy" width="900" height="700"></div></div></section>
<section class="alt"><div class="wrap grid3"><article class="card rv"><h3>Our Mission</h3><p>To transform business gatherings into strategic platforms for connection, innovation, and growth by delivering exceptional event experiences that exceed expectations and deliver measurable results for our clients.</p></article><article class="card rv"><h3>Our Vision</h3><p>To be the leading event management partner across the UK and EMEA, recognized for our innovative approach, strategic expertise, and ability to create meaningful connections that drive business success.</p></article><article class="card rv"><h3>Our Values</h3><p>Excellence, Integrity, Innovation, Collaboration, and Client-Centricity guide everything we do.</p></article></div></section>{stats()}'''
page("about", "About Level One Connect", "Learn about L1C — Level One Connect: our mission, vision, values and approach to executive events.", ab, crumb=[("About", "about.html")])

pr = "".join(f'<article class="card rv pr"><span class="n">0{i + 1}</span><h3>{p[1]}</h3><p>{p[2]}</p><ul class="ck">{"".join(f"<li>{x}</li>" for x in p[3])}</ul><p class="tag">Duration: {p[4]}</p></article>' for i, p in enumerate(PROC))
cs = "".join(f'<article class="card rv"><span class="tag">{c[1]}</span><h3>{c[0]}</h3><p>{c[2]}</p><div class="mt">{"".join(f"<div><b>{a}</b><span>{b}</span></div>" for a, b in c[3])}</div></article>' for c in CASES)
page("process", "Our Strategic Event Process", "A systematic four-step approach to delivering exceptional events that drive measurable business results.",
     hero("Our Strategic Event Process", "A systematic approach to delivering exceptional events that drive measurable business results.", IM["cons"]) + f'<section><div class="wrap"><div class="grid2">{pr}</div></div></section><section class="alt"><div class="wrap grid3">{"".join(f"<article class=\"card rv\"><h3>{x}</h3></article>" for x in PRIN)}</div></section><section><div class="wrap">{head("Success Stories")}<div class="grid3">{cs}</div></div></section>' + cta(), crumb=[("Process", "process.html")])

sec = lambda t, l: f'<section class="evs"><div class="wrap">{head(t)}<div class="elist">{"".join(erow(v) for v in l) or "<p>No events at the moment.</p>"}</div></div></section>'
page("events", "Events", "Upcoming, featured and past executive networking events, summits and dinners by L1C — Level One Connect.",
     hero("Events", "Executive networking, conferences, leadership dinners and business summits.", IM["net"]) + SEARCH + sec("Upcoming Events", [v for v in EVENTS if v["st"] == "upcoming"]) + '<div class="alt">' + sec("Featured Events", [v for v in EVENTS if v["st"] == "featured"]) + "</div>" + sec("Past Events", [v for v in EVENTS if v["st"] == "past"]), crumb=[("Events", "events.html")])
for v in EVENTS:
    ev = {"@context": "https://schema.org", "@type": "Event", "name": v["t"], "startDate": f'{v["d"]}T{v["tm"]}', "location": {"@type": "Place", "name": v["l"]}, "description": v["ds"], "image": v["i"], "organizer": {"@type": "Organization", "name": "Level One Connect", "url": SITE}}
    SPK = "<ul class=ck>" + "".join(f"<li>{e(x)}</li>" for x in v["sp"]) + "</ul>" if v.get("sp") else '<p class="mut">Speakers to be announced.</p>'
    AGD = "".join(f"<tr><td>{e(a)}</td><td>{e(b)}</td></tr>" for a, b in v.get("ag", [(v["tm"], "Welcome & arrival"), ("+1h", "Keynote / opening conversation"), ("+2h", "Roundtables & networking")]))
    GAL = "".join(f'<div class="pic rv"><img src="{x}" alt="Event photography" loading="lazy" width="600" height="400"></div>' for x in v.get("gal", (IM["dinner"], IM["net"], IM["conf"])))
    RSV = '<p class="mut">This event has taken place.</p>' + CTA("events.html", "See upcoming events") if v["st"] == "past" else CTA(v.get("reg", f'reserve.html?event={v["s"]}'), "Reserve a Seat")
    body = f'''{hero(v["t"], f'{fd(v["d"])} · {v["tm"]} · {v["l"]}', v["i"], v["c"])}<section><div class="wrap two-col"><div class="rv"><h2>About this event</h2><p>{v["ds"]}</p><h3>Speakers</h3>{SPK}<h3>Agenda</h3><table><tr><th>Time</th><th>Session</th></tr>{AGD}</table></div><aside class="card rv"><h3>Details</h3><p><b>Date</b><br>{fd(v["d"])}</p><p><b>Time</b><br>{v["tm"]}</p><p><b>Location</b><br>{v["l"]}</p>{RSV}<p></p>{CTA("contact.html#form", "Contact Our Team", "btn ghost dk")}</aside></div></section>
<section class="alt"><div class="wrap">{head("Gallery")}<div class="grid3">{GAL}</div></div></section>'''
    page("event-" + v["s"], v["t"], v["ds"], body, JS(ev), v["i"], [("Events", "events.html"), (v["t"], f'event-{v["s"]}.html')])
page("blog", "Insights & Perspectives", "Articles on event strategy, executive networking, leadership and technology from L1C — Level One Connect.",
     hero("Insights &amp; Perspectives", "Event strategy, executive networking, leadership, technology and industry insights.", IM["off"]) + f'<section><div class="wrap"><p class="cats">{"".join(f"<span class=tag>{c}</span>" for c in ("Event Strategy", "Executive Networking", "Leadership", "Technology", "Corporate Events", "Industry Insights"))}</p><div class="grid3">{"".join(bcard(p) for p in POSTS)}</div></div></section>', crumb=[("Blog", "blog.html")])
for p in POSTS:
    ar = {"@context": "https://schema.org", "@type": "Article", "headline": p["t"], "datePublished": p["d"], "author": {"@type": "Organization", "name": "L1C — Level One Connect"}, "image": p["i"], "publisher": {"@type": "Organization", "name": "Level One Connect"}}
    rel = "".join(bcard(x) for x in [y for y in POSTS if y is not p][:2])
    page("blog-" + p["s"], p["t"], p["ex"], f'{hero(p["t"], f"By the L1C team · {fd(p["d"])} · {p["r"]} min read", p["i"], p["c"])}<section><div class="wrap art"><img class="rv" src="{p["i"]}" alt="{e(p["t"])}" width="1000" height="560">{"".join(f"<p>{x}</p>" for x in p["b"])}</div></section><section class="alt"><div class="wrap">{head("Related Articles")}<div class="grid2">{rel}</div></div></section>' + cta(), JS(ar), p["i"], [("Blog", "blog.html"), (p["t"], f'blog-{p["s"]}.html')], "article")

page("contact", "Contact Us", "Contact L1C — Level One Connect to plan your conference, executive networking event or corporate gathering.",
     hero("Contact Us", "Ready to transform your next corporate event? Get in touch with our team today.", IM["off"]) + f'<section><div class="wrap two-col"><div class="rv"><h2>Let\'s Create Something Exceptional Together</h2><p>Whether you\'re planning a conference, executive networking event, or corporate gathering, our team is ready to help you create an unforgettable experience that delivers real business value.</p><h3>Email Us</h3><p><a href="mailto:{EMAIL}">{EMAIL}</a></p><h3>Call Us</h3>{"".join(f"<p>{p}</p>" for p in PHONES)}<h3>Location</h3><p>London, United Kingdom</p>{CTA("tel:" + PHONES[0].replace(" ", ""), "Call Now")}</div><div class="rv" id="form">{form()}</div></div></section>', crumb=[("Contact", "contact.html")])

TYPES = ["Conference / Summit", "Executive Networking", "Product Launch", "Gala Dinner / Awards", "Team Building", "Corporate Training", "Other"]
SIZES = ["10–50", "50–100", "100–200", "200–500", "500+"]
SERVICES = ["Full-service planning", "Venue sourcing", "Speaker management", "Invitations and guest list", "Registration and guest management", "Catering and hospitality", "AV and production", "Hybrid streaming", "Post-event reporting"]
START = hero("Start Your Event", "Tell us what you have in mind. The more detail you give us now, the more useful our first reply will be.", IM["lights"]) + '<section><div class="wrap sy"><form id="sf" class="form" novalidate data-subject="Event brief" data-ok="Thank you. We have your brief and a member of the team will reply by email." data-btn="Submit Your Brief" aria-label="Event brief">' + HP \
    + sub(1, "About the event", two(fld("type", "Event Type", "select", True, TYPES, "Select event type"), fld("ename", "Event name or working title", pl="Optional")),
          two(fld("goal", "Main goal", "select", True, ["Build relationships", "Generate leads or pipeline", "Launch a product", "Recognise or reward people", "Share knowledge", "Train or align a team", "Other"], "Select main goal"), fld("format", "Format", "select", True, ["In person", "Hybrid", "Virtual"], "Select format")),
          two(fld("size", "Estimated Attendees", "select", True, SIZES, "Select attendees"), fld("audience", "Who should attend?", req=True, pl="e.g. CIOs and heads of customer experience"))) \
    + sub(2, "When and where", two(fld("date", "Preferred date", "date"), fld("flex", "Date flexibility", "select", False, ["The date is fixed", "Flexible by a few days", "Flexible by a few weeks", "Not decided yet"])),
          two(fld("city", "Preferred city or region", pl="e.g. London"), fld("venue", "Venue preference", "select", False, ["Hotel", "Restaurant or private dining", "Conference centre", "Distinctive or unusual venue", "Need recommendations"])),
          fld("length", "Duration", "select", False, ["An evening", "Half a day", "A full day", "More than one day"])) \
    + sub(3, "Budget and support", fld("budget", "Estimated budget", "select", False, ["Under £10,000", "£10,000 – £25,000", "£25,000 – £50,000", "£50,000 – £100,000", "£100,000+", "Not sure yet"]), chk("services", "Services you may need", SERVICES)) \
    + sub(4, "Anything else", fld("msg", "Tell us about your event", "area", True, pl="Objectives, themes, speakers you have in mind, anything we should know"), fld("contactpref", "How should we reach you?", "select", False, ["Email", "Phone", "Either is fine"])) \
    + sub(5, "Your details", two(fld("name", "Full Name", req=True, ac="name"), fld("company", "Company", req=True, ac="organization")), two(fld("role", "Job title", ac="organization-title"), fld("email", "Email Address", "email", True, ac="email")), fld("phone", "Phone Number", "tel", mx=30, ac="tel"), CONSENT) \
    + '<button class="btn" type="submit"><span>Submit Your Brief</span></button><p class="st" role="status" aria-live="polite"></p></form><aside class="card rv side2"><h3>What happens next</h3><ol class="steps2"><li><b>We read your brief.</b> A member of the team reviews it and replies by email.</li><li><b>A short call.</b> We confirm goals, audience, timing and budget.</li><li><b>Your proposal.</b> A concept, timeline and costs for you to review.</li></ol><p class="mut">Prefer to talk first? Email <a href="mailto:' + EMAIL + '">' + EMAIL + '</a> or read about <a href="process.html">our process</a>.</p></aside></div></section>'
page("start-your-event", "Start Your Event", "Tell L1C about your event: goals, audience, date, venue and budget, and we will come back with a plan.", START, crumb=[("Start Your Event", "start-your-event.html")])
UPC = [v for v in EVENTS if v["st"] != "past"]
EVOPT = "".join(f'<option value="{e(v["t"])}" data-slug="{v["s"]}" data-when="{fd(v["d"])} · {v["tm"]}" data-loc="{e(v["l"])}">{e(v["t"])}, {fd(v["d"])}</option>' for v in UPC)
RES = hero("Reserve a Seat", "Choose the event, tell us who is coming and we will confirm your seat by email.", IM["dinner"]) + '<section><div class="wrap sy"><form id="rf" class="form" novalidate data-subject="Seat reservation" data-ok="Thank you. We have your request and will confirm your seat by email." data-btn="Reserve My Seat" aria-label="Seat reservation">' + HP \
    + f'<div class="f"><label for="event">Event *</label><select id="event" name="event" required><option value="">Select an event</option>{EVOPT}</select><small class="err"></small></div><p id="evinfo" class="mut"></p>' \
    + two(fld("name", "Full Name", req=True, ac="name"), fld("company", "Company", req=True, ac="organization")) + two(fld("role", "Job title", ac="organization-title"), fld("email", "Email Address", "email", True, ac="email")) \
    + two(fld("phone", "Phone Number", "tel", mx=30, ac="tel"), fld("seats", "Number of seats", "select", True, ["1", "2", "3", "4", "5 or more"])) \
    + fld("notes", "Dietary or accessibility requirements", "area", rows=3, pl="Optional") + CONSENT \
    + '<button class="btn" type="submit"><span>Reserve My Seat</span></button><p class="st" role="status" aria-live="polite"></p></form><aside class="card rv side2"><h3>Good to know</h3><ul class="ck"><li>Seats are confirmed by email.</li><li>Some events are by invitation, so we may ask a few questions first.</li><li>Booking for a group? Tell us in the form.</li></ul><a class="lk" href="events.html">All events →</a></aside></div></section>'
page("reserve", "Reserve a Seat", "Reserve a seat at an upcoming L1C event.", RES, crumb=[("Events", "events.html"), ("Reserve a Seat", "reserve.html")])
def legal(f, t, secs):
    b = "".join(f"<h2>{a}</h2><p>{c}</p>" for a, c in secs)
    page(f, t, f"{t} for L1C — Level One Connect.", hero(t, "Last updated: September 2026", IM["off"]) + f'<section><div class="wrap art">{b}</div></section>', crumb=[(t, f + ".html")])
legal("privacy", "Privacy Policy", [("Information we collect", "We collect the details you submit through our contact form (name, company, email, phone, event details) and basic technical data such as browser type."), ("Contact forms", "Form data is used only to respond to your enquiry."), ("Cookies", "See our Cookie Policy. Non-essential cookies are used only with consent."), ("Analytics", "This website does not include analytics by default. If added, it will be disclosed here and require consent."), ("How we use information", "To respond to enquiries, provide event services and improve our website."), ("Data retention", "We keep enquiry data only as long as needed for the purposes above or as required by law."), ("Security", "We use reasonable technical and organisational measures. No online transmission is fully secure."), ("Third-party services", "This site loads fonts from Google Fonts and images from Unsplash, and may use a form-processing service."), ("Your rights", "Depending on your location you may request access, correction or deletion of your data."), ("Contact", f"Contact us at {EMAIL}."), ("Policy updates", "We may update this policy; the date above shows the latest revision.")])
legal("cookies", "Cookie Policy", [("Essential cookies", "Required for the website to function. This site currently sets none."), ("Functional cookies", "Remember preferences such as your cookie choice."), ("Analytics cookies", "Not used currently. If added, they will load only after your consent."), ("Third-party cookies", "Embedded third-party services may set their own cookies."), ("Cookie management", "You can delete or block cookies in your browser settings."), ("Consent", "Non-essential cookies are only set with your consent, which you can withdraw at any time.")])
legal("terms", "Terms & Conditions", [("Website usage", "By using this website you agree to these terms and to use it lawfully."), ("Intellectual property", "All content, logos and designs belong to L1C — Level One Connect or its licensors."), ("Event services", "Event services are provided under separate written agreements."), ("Enquiries and booking", "Submitting an enquiry does not create a booking or contract."), ("Third-party services", "We are not responsible for third-party services or content."), ("Liability", "To the extent permitted by law, we are not liable for losses from use of this website."), ("External links", "External sites are outside our control."), ("Website changes", "We may modify the website and these terms at any time."), ("Governing law", "[Governing law and jurisdiction to be specified.]"), ("Contact information", f"{EMAIL} · London, United Kingdom")])
page("404", "Page Not Found", "This page doesn't exist.", f'<section class="nf glow"><div class="wrap c"><h1>404</h1><h2>This page doesn\'t exist.</h2>{CTA("index.html", "Back to Home")}</div></section>')
os.rename(f"{OUT}/404.html", f"{OUT}/404.html")

pages = [f[len(OUT) + 1:-5] for f in glob.glob(OUT + "/*.html") if not f.endswith("404.html")]
open(f"{OUT}/sitemap.xml", "w").write('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + "".join(f"<url><loc>{SITE}/{'' if p == 'index' else p + '.html'}</loc></url>" for p in sorted(pages)) + "</urlset>")
open(f"{OUT}/robots.txt", "w").write(f"User-agent: *\nAllow: /\nSitemap: {SITE}/sitemap.xml\n")
open(f"{OUT}/README.txt", "w").write("L1C website (static). CSS and JS are inlined in every page. Replace assets/logo.* with the official logo, set the real domain/email in build.py, set window.L1C_ENDPOINT in build.py (CFG), run `python3 build.py`.\nSecurity headers (CSP, X-Frame-Options, HSTS) must be set at host/CDN level; set the CSP header at host level too (it is not in the HTML so the site also works when opened locally).\n")
